"""Compatibility exports for audit actions.

Keep the original import style (`from app.audit import actions`) while sourcing
all values from `app.core.constants`.
"""

from app.core.constants import AUDIT_ACTION_ASSET_UPLOAD as ASSET_UPLOAD
from app.core.constants import AUDIT_ACTION_EDGE_PULL_MODEL as EDGE_PULL_MODEL
from app.core.constants import AUDIT_ACTION_EDGE_PULL_TASKS as EDGE_PULL_TASKS
from app.core.constants import AUDIT_ACTION_EDGE_PUSH_RESULTS as EDGE_PUSH_RESULTS
from app.core.constants import AUDIT_ACTION_ASSISTANT_PLAN as ASSISTANT_PLAN
from app.core.constants import AUDIT_ACTION_AI_KNOWLEDGE_UPDATE as AI_KNOWLEDGE_UPDATE
from app.core.constants import AUDIT_ACTION_AI_PROVIDER_TEST as AI_PROVIDER_TEST
from app.core.constants import AUDIT_ACTION_AI_SETTINGS_UPDATE as AI_SETTINGS_UPDATE
from app.core.constants import AUDIT_ACTION_DATA_GOVERNANCE_EXECUTE as DATA_GOVERNANCE_EXECUTE
from app.core.constants import AUDIT_ACTION_DATA_GOVERNANCE_PREVIEW as DATA_GOVERNANCE_PREVIEW
from app.core.constants import AUDIT_ACTION_LOGIN as LOGIN
from app.core.constants import AUDIT_ACTION_MODEL_APPROVE as MODEL_APPROVE
from app.core.constants import AUDIT_ACTION_MODEL_DOWNLOAD as MODEL_DOWNLOAD
from app.core.constants import AUDIT_ACTION_MODEL_EVIDENCE_EXPORT as MODEL_EVIDENCE_EXPORT
from app.core.constants import AUDIT_ACTION_MODEL_REGISTER as MODEL_REGISTER
from app.core.constants import AUDIT_ACTION_MODEL_REJECT as MODEL_REJECT
from app.core.constants import AUDIT_ACTION_MODEL_RECOMMEND as MODEL_RECOMMEND
from app.core.constants import AUDIT_ACTION_MODEL_REQUEST_EVIDENCE as MODEL_REQUEST_EVIDENCE
from app.core.constants import AUDIT_ACTION_RESULT_DATASET_EXPORT as RESULT_DATASET_EXPORT
from app.core.constants import AUDIT_ACTION_RESULT_REVIEW_SAVE as RESULT_REVIEW_SAVE
from app.core.constants import AUDIT_ACTION_DATASET_VERSION_CREATE as DATASET_VERSION_CREATE
from app.core.constants import AUDIT_ACTION_DATASET_VERSION_ROLLBACK as DATASET_VERSION_ROLLBACK
from app.core.constants import AUDIT_ACTION_DATASET_VERSION_RECOMMEND as DATASET_VERSION_RECOMMEND
from app.core.constants import AUDIT_ACTION_MODEL_RELEASE as MODEL_RELEASE
from app.core.constants import AUDIT_ACTION_MODEL_SUBMIT as MODEL_SUBMIT
from app.core.constants import AUDIT_ACTION_ORCHESTRATOR_RUN as ORCHESTRATOR_RUN
from app.core.constants import AUDIT_ACTION_PIPELINE_REGISTER as PIPELINE_REGISTER
from app.core.constants import AUDIT_ACTION_PIPELINE_RELEASE as PIPELINE_RELEASE
from app.core.constants import AUDIT_ACTION_REVIEW_QUEUE_ENQUEUE as REVIEW_QUEUE_ENQUEUE
from app.core.constants import AUDIT_ACTION_RESULT_EXPORT as RESULT_EXPORT
from app.core.constants import AUDIT_ACTION_LLM_CATALOG_REFRESH as LLM_CATALOG_REFRESH
from app.core.constants import AUDIT_ACTION_LLM_DOWNLOAD_REQUEST as LLM_DOWNLOAD_REQUEST
from app.core.constants import AUDIT_ACTION_LLM_DOWNLOAD_CANCEL as LLM_DOWNLOAD_CANCEL
from app.core.constants import AUDIT_ACTION_LLM_LOCAL_DELETE as LLM_LOCAL_DELETE
from app.core.constants import AUDIT_ACTION_TASK_CREATE as TASK_CREATE
from app.core.constants import AUDIT_ACTION_TASK_DELETE as TASK_DELETE
from app.core.constants import AUDIT_ACTION_TASK_ROUTE as TASK_ROUTE
from app.core.constants import AUDIT_ACTION_TRAINING_JOB_ASSIGN as TRAINING_JOB_ASSIGN
from app.core.constants import AUDIT_ACTION_TRAINING_JOB_CANCEL as TRAINING_JOB_CANCEL
from app.core.constants import AUDIT_ACTION_TRAINING_JOB_CREATE as TRAINING_JOB_CREATE
from app.core.constants import AUDIT_ACTION_TRAINING_JOB_REASSIGN as TRAINING_JOB_REASSIGN
from app.core.constants import AUDIT_ACTION_TRAINING_JOB_RETRY as TRAINING_JOB_RETRY
from app.core.constants import AUDIT_ACTION_TRAINING_JOB_TIMEOUT as TRAINING_JOB_TIMEOUT
from app.core.constants import AUDIT_ACTION_TRAINING_JOB_UPDATE as TRAINING_JOB_UPDATE
from app.core.constants import AUDIT_ACTION_TRAINING_ASSET_PULL as TRAINING_ASSET_PULL
from app.core.constants import AUDIT_ACTION_TRAINING_CANDIDATE_UPLOAD as TRAINING_CANDIDATE_UPLOAD
from app.core.constants import AUDIT_ACTION_TRAINING_MODEL_PULL as TRAINING_MODEL_PULL
from app.core.constants import AUDIT_ACTION_TRAINING_WORKER_HEARTBEAT as TRAINING_WORKER_HEARTBEAT
from app.core.constants import AUDIT_ACTION_TRAINING_WORKER_CLEANUP as TRAINING_WORKER_CLEANUP
from app.core.constants import AUDIT_ACTION_TRAINING_WORKER_REGISTER as TRAINING_WORKER_REGISTER
from app.core.constants import AUDIT_ACTION_TRAINING_WORKER_UNHEALTHY as TRAINING_WORKER_UNHEALTHY

ALL_AUDIT_ACTIONS = (
    LOGIN,
    ASSET_UPLOAD,
    TASK_CREATE,
    MODEL_SUBMIT,
    MODEL_APPROVE,
    MODEL_REJECT,
    MODEL_REQUEST_EVIDENCE,
    MODEL_EVIDENCE_EXPORT,
    MODEL_REGISTER,
    MODEL_RELEASE,
    MODEL_DOWNLOAD,
    MODEL_RECOMMEND,
    RESULT_EXPORT,
    RESULT_DATASET_EXPORT,
    RESULT_REVIEW_SAVE,
    DATASET_VERSION_CREATE,
    DATASET_VERSION_ROLLBACK,
    DATASET_VERSION_RECOMMEND,
    TASK_DELETE,
    TASK_ROUTE,
    TRAINING_JOB_CREATE,
    TRAINING_JOB_ASSIGN,
    TRAINING_JOB_UPDATE,
    TRAINING_JOB_CANCEL,
    TRAINING_JOB_RETRY,
    TRAINING_JOB_REASSIGN,
    TRAINING_JOB_TIMEOUT,
    TRAINING_ASSET_PULL,
    TRAINING_MODEL_PULL,
    TRAINING_CANDIDATE_UPLOAD,
    TRAINING_WORKER_REGISTER,
    TRAINING_WORKER_HEARTBEAT,
    TRAINING_WORKER_CLEANUP,
    TRAINING_WORKER_UNHEALTHY,
    PIPELINE_REGISTER,
    PIPELINE_RELEASE,
    ORCHESTRATOR_RUN,
    REVIEW_QUEUE_ENQUEUE,
    EDGE_PULL_TASKS,
    EDGE_PULL_MODEL,
    EDGE_PUSH_RESULTS,
    ASSISTANT_PLAN,
    AI_SETTINGS_UPDATE,
    AI_PROVIDER_TEST,
    AI_KNOWLEDGE_UPDATE,
    LLM_CATALOG_REFRESH,
    LLM_DOWNLOAD_REQUEST,
    LLM_DOWNLOAD_CANCEL,
    LLM_LOCAL_DELETE,
    DATA_GOVERNANCE_PREVIEW,
    DATA_GOVERNANCE_EXECUTE,
)
