"""Centralized constants to keep RBAC/status/audit values in a single source."""

# Canonical permissions (frontend and backend must stay aligned).
PERMISSION_DASHBOARD_VIEW = "dashboard.view"
PERMISSION_MODEL_VIEW = "model.view"
PERMISSION_MODEL_SUBMIT = "model.submit"
PERMISSION_MODEL_APPROVE = "model.approve"
PERMISSION_MODEL_RELEASE = "model.release"
PERMISSION_ASSET_UPLOAD = "asset.upload"
PERMISSION_TASK_CREATE = "task.create"
PERMISSION_RESULT_READ = "result.read"
PERMISSION_AUDIT_READ = "audit.read"
PERMISSION_DEVICE_READ = "device.read"
PERMISSION_SETTINGS_VIEW = "settings.view"
PERMISSION_DATA_L3_READ = "data.l3.read"
PERMISSION_TRAINING_JOB_VIEW = "training.job.view"
PERMISSION_TRAINING_JOB_CREATE = "training.job.create"
PERMISSION_TRAINING_WORKER_MANAGE = "training.worker.manage"

ALL_PERMISSIONS = (
    PERMISSION_DASHBOARD_VIEW,
    PERMISSION_MODEL_VIEW,
    PERMISSION_MODEL_SUBMIT,
    PERMISSION_MODEL_APPROVE,
    PERMISSION_MODEL_RELEASE,
    PERMISSION_ASSET_UPLOAD,
    PERMISSION_TASK_CREATE,
    PERMISSION_RESULT_READ,
    PERMISSION_AUDIT_READ,
    PERMISSION_DEVICE_READ,
    PERMISSION_SETTINGS_VIEW,
    PERMISSION_DATA_L3_READ,
    PERMISSION_TRAINING_JOB_VIEW,
    PERMISSION_TRAINING_JOB_CREATE,
    PERMISSION_TRAINING_WORKER_MANAGE,
)


# Model lifecycle statuses.
MODEL_STATUS_REGISTERED = "REGISTERED"
MODEL_STATUS_SUBMITTED = "SUBMITTED"
MODEL_STATUS_REJECTED = "REJECTED"
MODEL_STATUS_APPROVED = "APPROVED"
MODEL_STATUS_RELEASED = "RELEASED"

MODEL_TYPE_EXPERT = "expert"
MODEL_TYPE_ROUTER = "router"

MODEL_STATUSES = (
    MODEL_STATUS_REGISTERED,
    MODEL_STATUS_SUBMITTED,
    MODEL_STATUS_REJECTED,
    MODEL_STATUS_APPROVED,
    MODEL_STATUS_RELEASED,
)

MODEL_TYPES = (
    MODEL_TYPE_EXPERT,
    MODEL_TYPE_ROUTER,
)


# Model release statuses.
MODEL_RELEASE_STATUS_RELEASED = "RELEASED"


# Pipeline lifecycle statuses.
PIPELINE_STATUS_DRAFT = "DRAFT"
PIPELINE_STATUS_RELEASED = "RELEASED"

PIPELINE_STATUSES = (
    PIPELINE_STATUS_DRAFT,
    PIPELINE_STATUS_RELEASED,
)


# Inference task statuses.
TASK_STATUS_PENDING = "PENDING"
TASK_STATUS_DISPATCHED = "DISPATCHED"
TASK_STATUS_SUCCEEDED = "SUCCEEDED"
TASK_STATUS_FAILED = "FAILED"

TASK_STATUSES = (
    TASK_STATUS_PENDING,
    TASK_STATUS_DISPATCHED,
    TASK_STATUS_SUCCEEDED,
    TASK_STATUS_FAILED,
)
TASK_TERMINAL_STATUSES = (
    TASK_STATUS_SUCCEEDED,
    TASK_STATUS_FAILED,
)


# Training job statuses.
TRAINING_JOB_STATUS_PENDING = "PENDING"
TRAINING_JOB_STATUS_DISPATCHED = "DISPATCHED"
TRAINING_JOB_STATUS_RUNNING = "RUNNING"
TRAINING_JOB_STATUS_SUCCEEDED = "SUCCEEDED"
TRAINING_JOB_STATUS_FAILED = "FAILED"
TRAINING_JOB_STATUS_CANCELLED = "CANCELLED"

TRAINING_JOB_STATUSES = (
    TRAINING_JOB_STATUS_PENDING,
    TRAINING_JOB_STATUS_DISPATCHED,
    TRAINING_JOB_STATUS_RUNNING,
    TRAINING_JOB_STATUS_SUCCEEDED,
    TRAINING_JOB_STATUS_FAILED,
    TRAINING_JOB_STATUS_CANCELLED,
)

TRAINING_JOB_TERMINAL_STATUSES = (
    TRAINING_JOB_STATUS_SUCCEEDED,
    TRAINING_JOB_STATUS_FAILED,
    TRAINING_JOB_STATUS_CANCELLED,
)


# Training worker statuses.
TRAINING_WORKER_STATUS_ACTIVE = "ACTIVE"
TRAINING_WORKER_STATUS_INACTIVE = "INACTIVE"
TRAINING_WORKER_STATUS_UNHEALTHY = "UNHEALTHY"

TRAINING_WORKER_STATUSES = (
    TRAINING_WORKER_STATUS_ACTIVE,
    TRAINING_WORKER_STATUS_INACTIVE,
    TRAINING_WORKER_STATUS_UNHEALTHY,
)


# Audit actions.
AUDIT_ACTION_LOGIN = "LOGIN"
AUDIT_ACTION_ASSET_UPLOAD = "ASSET_UPLOAD"
AUDIT_ACTION_TASK_CREATE = "TASK_CREATE"
AUDIT_ACTION_MODEL_SUBMIT = "MODEL_SUBMIT"
AUDIT_ACTION_MODEL_APPROVE = "MODEL_APPROVE"
AUDIT_ACTION_MODEL_REJECT = "MODEL_REJECT"
AUDIT_ACTION_MODEL_REQUEST_EVIDENCE = "MODEL_REQUEST_EVIDENCE"
AUDIT_ACTION_MODEL_EVIDENCE_EXPORT = "MODEL_EVIDENCE_EXPORT"
AUDIT_ACTION_MODEL_REGISTER = "MODEL_REGISTER"
AUDIT_ACTION_MODEL_RELEASE = "MODEL_RELEASE"
AUDIT_ACTION_MODEL_DOWNLOAD = "MODEL_DOWNLOAD"
AUDIT_ACTION_MODEL_RECOMMEND = "MODEL_RECOMMEND"
AUDIT_ACTION_RESULT_EXPORT = "RESULT_EXPORT"
AUDIT_ACTION_RESULT_DATASET_EXPORT = "RESULT_DATASET_EXPORT"
AUDIT_ACTION_RESULT_REVIEW_SAVE = "RESULT_REVIEW_SAVE"
AUDIT_ACTION_DATASET_VERSION_CREATE = "DATASET_VERSION_CREATE"
AUDIT_ACTION_DATASET_VERSION_RECOMMEND = "DATASET_VERSION_RECOMMEND"
AUDIT_ACTION_DATASET_VERSION_ROLLBACK = "DATASET_VERSION_ROLLBACK"
AUDIT_ACTION_TASK_DELETE = "TASK_DELETE"
AUDIT_ACTION_TASK_ROUTE = "TASK_ROUTE"
AUDIT_ACTION_PIPELINE_REGISTER = "PIPELINE_REGISTER"
AUDIT_ACTION_PIPELINE_RELEASE = "PIPELINE_RELEASE"
AUDIT_ACTION_ORCHESTRATOR_RUN = "ORCHESTRATOR_RUN"
AUDIT_ACTION_REVIEW_QUEUE_ENQUEUE = "REVIEW_QUEUE_ENQUEUE"
AUDIT_ACTION_EDGE_PULL_TASKS = "EDGE_PULL_TASKS"
AUDIT_ACTION_EDGE_PULL_MODEL = "EDGE_PULL_MODEL"
AUDIT_ACTION_EDGE_PUSH_RESULTS = "EDGE_PUSH_RESULTS"
AUDIT_ACTION_TRAINING_JOB_CREATE = "TRAINING_JOB_CREATE"
AUDIT_ACTION_TRAINING_JOB_ASSIGN = "TRAINING_JOB_ASSIGN"
AUDIT_ACTION_TRAINING_JOB_UPDATE = "TRAINING_JOB_UPDATE"
AUDIT_ACTION_TRAINING_JOB_CANCEL = "TRAINING_JOB_CANCEL"
AUDIT_ACTION_TRAINING_JOB_RETRY = "TRAINING_JOB_RETRY"
AUDIT_ACTION_TRAINING_JOB_REASSIGN = "TRAINING_JOB_REASSIGN"
AUDIT_ACTION_TRAINING_JOB_TIMEOUT = "TRAINING_JOB_TIMEOUT"
AUDIT_ACTION_TRAINING_WORKER_REGISTER = "TRAINING_WORKER_REGISTER"
AUDIT_ACTION_TRAINING_WORKER_HEARTBEAT = "TRAINING_WORKER_HEARTBEAT"
AUDIT_ACTION_TRAINING_WORKER_UNHEALTHY = "TRAINING_WORKER_UNHEALTHY"
AUDIT_ACTION_TRAINING_WORKER_CLEANUP = "TRAINING_WORKER_CLEANUP"
AUDIT_ACTION_TRAINING_ASSET_PULL = "TRAINING_ASSET_PULL"
AUDIT_ACTION_TRAINING_MODEL_PULL = "TRAINING_MODEL_PULL"
AUDIT_ACTION_TRAINING_CANDIDATE_UPLOAD = "TRAINING_CANDIDATE_UPLOAD"
AUDIT_ACTION_DATA_GOVERNANCE_PREVIEW = "DATA_GOVERNANCE_PREVIEW"
AUDIT_ACTION_DATA_GOVERNANCE_EXECUTE = "DATA_GOVERNANCE_EXECUTE"
AUDIT_ACTION_ASSISTANT_PLAN = "ASSISTANT_PLAN"
AUDIT_ACTION_AI_SETTINGS_UPDATE = "AI_SETTINGS_UPDATE"
AUDIT_ACTION_AI_PROVIDER_TEST = "AI_PROVIDER_TEST"
AUDIT_ACTION_AI_KNOWLEDGE_UPDATE = "AI_KNOWLEDGE_UPDATE"
AUDIT_ACTION_LLM_CATALOG_REFRESH = "LLM_CATALOG_REFRESH"
AUDIT_ACTION_LLM_DOWNLOAD_REQUEST = "LLM_DOWNLOAD_REQUEST"
AUDIT_ACTION_LLM_DOWNLOAD_CANCEL = "LLM_DOWNLOAD_CANCEL"
AUDIT_ACTION_LLM_LOCAL_DELETE = "LLM_LOCAL_DELETE"
