"""Centralized constants to keep RBAC/status/audit values in a single source."""

# Canonical permissions (frontend and backend must stay aligned).
PERMISSION_DASHBOARD_VIEW = "dashboard.view"
PERMISSION_MODEL_VIEW = "model.view"
PERMISSION_MODEL_SUBMIT = "model.submit"
PERMISSION_MODEL_APPROVE = "model.approve"
PERMISSION_MODEL_RELEASE = "model.release"
PERMISSION_ASSET_UPLOAD = "asset.upload"
PERMISSION_TASK_CREATE = "task.create"
PERMISSION_RESULT_READ = "result.read"
PERMISSION_AUDIT_READ = "audit.read"
PERMISSION_DATA_L3_READ = "data.l3.read"

ALL_PERMISSIONS = (
    PERMISSION_DASHBOARD_VIEW,
    PERMISSION_MODEL_VIEW,
    PERMISSION_MODEL_SUBMIT,
    PERMISSION_MODEL_APPROVE,
    PERMISSION_MODEL_RELEASE,
    PERMISSION_ASSET_UPLOAD,
    PERMISSION_TASK_CREATE,
    PERMISSION_RESULT_READ,
    PERMISSION_AUDIT_READ,
    PERMISSION_DATA_L3_READ,
)


# Model lifecycle statuses.
MODEL_STATUS_REGISTERED = "REGISTERED"
MODEL_STATUS_SUBMITTED = "SUBMITTED"
MODEL_STATUS_APPROVED = "APPROVED"
MODEL_STATUS_RELEASED = "RELEASED"

MODEL_TYPE_EXPERT = "expert"
MODEL_TYPE_ROUTER = "router"

MODEL_STATUSES = (
    MODEL_STATUS_REGISTERED,
    MODEL_STATUS_SUBMITTED,
    MODEL_STATUS_APPROVED,
    MODEL_STATUS_RELEASED,
)

MODEL_TYPES = (
    MODEL_TYPE_EXPERT,
    MODEL_TYPE_ROUTER,
)


# Model release statuses.
MODEL_RELEASE_STATUS_RELEASED = "RELEASED"


# Pipeline lifecycle statuses.
PIPELINE_STATUS_DRAFT = "DRAFT"
PIPELINE_STATUS_RELEASED = "RELEASED"

PIPELINE_STATUSES = (
    PIPELINE_STATUS_DRAFT,
    PIPELINE_STATUS_RELEASED,
)


# Inference task statuses.
TASK_STATUS_PENDING = "PENDING"
TASK_STATUS_DISPATCHED = "DISPATCHED"
TASK_STATUS_SUCCEEDED = "SUCCEEDED"
TASK_STATUS_FAILED = "FAILED"

TASK_STATUSES = (
    TASK_STATUS_PENDING,
    TASK_STATUS_DISPATCHED,
    TASK_STATUS_SUCCEEDED,
    TASK_STATUS_FAILED,
)
TASK_TERMINAL_STATUSES = (
    TASK_STATUS_SUCCEEDED,
    TASK_STATUS_FAILED,
)


# Audit actions.
AUDIT_ACTION_LOGIN = "LOGIN"
AUDIT_ACTION_ASSET_UPLOAD = "ASSET_UPLOAD"
AUDIT_ACTION_TASK_CREATE = "TASK_CREATE"
AUDIT_ACTION_MODEL_SUBMIT = "MODEL_SUBMIT"
AUDIT_ACTION_MODEL_APPROVE = "MODEL_APPROVE"
AUDIT_ACTION_MODEL_REGISTER = "MODEL_REGISTER"
AUDIT_ACTION_MODEL_RELEASE = "MODEL_RELEASE"
AUDIT_ACTION_MODEL_DOWNLOAD = "MODEL_DOWNLOAD"
AUDIT_ACTION_MODEL_RECOMMEND = "MODEL_RECOMMEND"
AUDIT_ACTION_RESULT_EXPORT = "RESULT_EXPORT"
AUDIT_ACTION_TASK_DELETE = "TASK_DELETE"
AUDIT_ACTION_TASK_ROUTE = "TASK_ROUTE"
AUDIT_ACTION_PIPELINE_REGISTER = "PIPELINE_REGISTER"
AUDIT_ACTION_PIPELINE_RELEASE = "PIPELINE_RELEASE"
AUDIT_ACTION_ORCHESTRATOR_RUN = "ORCHESTRATOR_RUN"
AUDIT_ACTION_REVIEW_QUEUE_ENQUEUE = "REVIEW_QUEUE_ENQUEUE"
AUDIT_ACTION_EDGE_PULL_TASKS = "EDGE_PULL_TASKS"
AUDIT_ACTION_EDGE_PULL_MODEL = "EDGE_PULL_MODEL"
AUDIT_ACTION_EDGE_PUSH_RESULTS = "EDGE_PUSH_RESULTS"
